In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('data/score.csv', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [9]:
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [10]:
df = pd.read_csv('data/경찰청_범죄 발생 지역별 통계_20221231.csv', encoding='euc-kr')
df

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,35,29,16,14,1,6,8,2,...,1,2,1,2,5,0,1,3,4,19
1,강력범죄,살인미수등,68,24,15,38,2,11,7,3,...,2,0,3,1,11,1,4,4,1,43
2,강력범죄,강도,118,43,31,30,10,17,10,2,...,1,1,0,0,12,5,1,4,1,28
3,강력범죄,강간,1200,347,215,340,152,200,112,26,...,6,12,36,41,77,19,17,78,18,375
4,강력범죄,유사강간,219,83,43,61,32,34,14,6,...,0,2,3,2,14,4,8,13,3,52
5,강력범죄,강제추행,4358,1064,648,1030,391,500,311,73,...,23,25,66,97,232,38,84,201,18,848
6,강력범죄,기타강간강제추행등,35,14,9,16,8,2,10,1,...,1,1,0,1,5,2,0,3,1,23
7,강력범죄,방화,217,89,50,70,35,40,28,8,...,5,5,4,10,24,5,9,20,0,114
8,절도범죄,절도범죄,37594,13699,9792,8895,5204,6034,3283,1110,...,308,342,1158,2114,3426,387,886,2247,43,9454
9,폭력범죄,상해,3353,2478,1568,1545,641,831,683,119,...,121,113,221,251,635,134,213,351,16,2612
10,폭력범죄,폭행,26509,8474,5629,8040,3430,4166,2574,400,...,168,246,803,800,2289,334,625,2169,53,5704
11,폭력범죄,체포감금,243,66,41,100,33,31,35,3,...,1,3,3,9,18,0,4,21,4,58
12,폭력범죄,협박,4162,1402,933,1411,424,595,397,86,...,55,54,141,127,311,61,109,386,82,1345
13,폭력범죄,약취유인,72,17,7,18,8,2,5,2,...,0,0,1,5,1,0,0,1,1,11
14,폭력범죄,폭력행위등,1075,572,277,501,196,211,198,25,...,20,17,47,33,127,47,56,97,4,352
15,폭력범죄,공갈,1056,503,189,591,113,232,71,25,...,13,7,50,59,126,21,28,72,465,358
16,폭력범죄,손괴,10240,3730,2716,3089,1457,1696,1079,250,...,102,107,302,387,1095,155,374,881,13,3486
17,지능범죄,직무유기,353,130,64,95,31,33,18,26,...,2,1,8,4,14,15,0,16,37,166
18,지능범죄,직권남용,392,156,47,78,64,51,19,21,...,2,0,18,10,14,5,4,19,58,128
19,지능범죄,증수뢰,71,17,7,21,11,13,7,1,...,0,0,3,2,7,0,0,1,11,31
20,지능범죄,통화,172,20,27,29,10,7,1,3,...,0,0,0,1,2,0,0,2,12,13
21,지능범죄,문서인장,2033,897,459,581,319,336,206,70,...,27,19,62,57,184,28,35,146,626,843
22,지능범죄,유가증권인지,25,7,3,0,1,0,0,0,...,0,0,0,1,0,0,0,1,2,1
23,지능범죄,사기,52034,26847,14836,16652,8249,11734,5615,1528,...,568,625,2055,2583,7204,1193,1599,3996,25191,16295
24,지능범죄,횡령,16368,4469,2643,4175,1666,1456,759,248,...,44,51,265,231,1069,117,225,646,993,2080
25,지능범죄,배임,791,273,106,184,112,105,72,13,...,7,7,17,17,70,9,12,52,176,263
26,풍속범죄,성풍속범죄,4924,1602,1125,1507,577,733,449,120,...,27,34,126,112,391,39,82,216,786,747
27,풍속범죄,도박범죄,545,384,138,239,102,181,248,13,...,2,6,23,7,53,9,13,49,110,290
28,특별경제범죄,특별경제범죄,10374,3996,1917,3025,1332,1226,794,169,...,55,66,277,376,796,114,186,595,2460,2025
29,마약범죄,마약범죄,2821,856,306,1062,129,101,107,29,...,23,18,51,55,226,62,7,44,71,1000
30,보건범죄,보건범죄,4260,2581,777,1048,431,303,347,60,...,71,54,93,104,291,68,47,170,108,856
31,환경범죄,환경범죄,50,243,16,87,7,23,29,7,...,36,46,7,31,71,33,11,21,49,574
32,교통범죄,교통범죄,32013,12176,12610,11926,7827,6389,5754,1031,...,574,751,1573,1376,4023,825,1382,3052,323,20094
33,노동범죄,노동범죄,83,37,19,14,9,21,1,0,...,1,1,6,7,5,0,9,27,13,32
34,안보범죄,안보범죄,61,13,6,7,4,4,4,2,...,0,0,0,1,1,0,2,1,12,9
35,선거범죄,선거범죄,552,138,128,104,104,50,50,14,...,3,18,25,16,53,7,21,29,124,461
36,병역범죄,병역범죄,935,164,207,400,109,68,64,20,...,8,4,25,13,56,9,12,27,303,214
37,기타범죄,기타범죄,48367,24440,8821,17865,5177,5758,4016,1009,...,401,527,1348,1286,5339,3261,1455,3575,8013,23631

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 89 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   범죄대분류   38 non-null     object
 1   범죄중분류   38 non-null     object
 2   서울      38 non-null     int64
 3   부산      38 non-null     int64
 4   대구      38 non-null     int64
 5   인천      38 non-null     int64
 6   광주      38 non-null     int64
 7   대전      38 non-null     int64
 8   울산      38 non-null     int64
 9   세종      38 non-null     int64
 10  경기 고양   38 non-null     int64
 11  경기 과천   38 non-null     int64
 12  경기 광명   38 non-null     int64
 13  경기 광주   38 non-null     int64
 14  경기 구리   38 non-null     int64
 15  경기 군포   38 non-null     int64
 16  경기 김포   38 non-null     int64
 17  경기 남양주  38 non-null     int64
 18  경기 동두천  38 non-null     int64
 19  경기 부천   38 non-null     int64
 20  경기 성남   38 non-null     int64
 21  경기 수원   38 non-null     int64
 22  경기 시흥   38 non-null     int64
 23  경기 안산   38 non-null     int64
 24  경기 안성   38 non-null     int64
 25  경기 안양   38 non-null     int64
 26  경기 양주   38 non-null     int64
 27  경기 여주   38 non-null     int64
 28  경기 오산   38 non-null     int64
 29  경기 용인   38 non-null     int64
 30  경기 의왕   38 non-null     int64
 31  경기 의정부  38 non-null     int64
 32  경기 이천   38 non-null     int64
 33  경기 파주   38 non-null     int64
 34  경기 평택   38 non-null     int64
 35  경기 포천   38 non-null     int64
 36  경기 하남   38 non-null     int64
 37  경기 화성   38 non-null     int64
 38  강원 강릉   38 non-null     int64
 39  강원 동해   38 non-null     int64
 40  강원 삼척   38 non-null     int64
 41  강원 속초   38 non-null     int64
 42  강원 원주   38 non-null     int64
 43  강원 춘천   38 non-null     int64
 44  강원 태백   38 non-null     int64
 45  충북 제천   38 non-null     int64
 46  충북 청주   38 non-null     int64
 47  충북 충주   38 non-null     int64
 48  충남 계룡   38 non-null     int64
 49  충남 공주   38 non-null     int64
 50  충남 논산   38 non-null     int64
 51  충남 당진   38 non-null     int64
 52  충남 보령   38 non-null     int64
 53  충남 서산   38 non-null     int64
 54  충남 아산   38 non-null     int64
 55  충남 천안   38 non-null     int64
 56  전북 군산   38 non-null     int64
 57  전북 김제   38 non-null     int64
 58  전북 남원   38 non-null     int64
 59  전북 익산   38 non-null     int64
 60  전북 전주   38 non-null     int64
 61  전북 정읍   38 non-null     int64
 62  전남 광양   38 non-null     int64
 63  전남 나주   38 non-null     int64
 64  전남 목포   38 non-null     int64
 65  전남 순천   38 non-null     int64
 66  전남 여수   38 non-null     int64
 67  경북 경산   38 non-null     int64
 68  경북 경주   38 non-null     int64
 69  경북 구미   38 non-null     int64
 70  경북 김천   38 non-null     int64
 71  경북 문경   38 non-null     int64
 72  경북 상주   38 non-null     int64
 73  경북 안동   38 non-null     int64
 74  경북 영주   38 non-null     int64
 75  경북 영천   38 non-null     int64
 76  경북 포항   38 non-null     int64
 77  경남 거제   38 non-null     int64
 78  경남 김해   38 non-null     int64
 79  경남 밀양   38 non-null     int64
 80  경남 사천   38 non-null     int64
 81  경남 양산   38 non-null     int64
 82  경남 진주   38 non-null     int64
 83  경남 창원   38 non-null     int64
 84  경남 통영   38 non-null     int64
 85  제주 서귀포  38 non-null     int64
 86  제주 제주   38 non-null     int64
 87  기타도시    38 non-null     int64
 88  도시이외    38 non-null     int64
dtypes: int64(87), object(2)
memory usage: 26.6+ KB

In [13]:
df.head()

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,35,29,16,14,1,6,8,2,...,1,2,1,2,5,0,1,3,4,19
1,강력범죄,살인미수등,68,24,15,38,2,11,7,3,...,2,0,3,1,11,1,4,4,1,43
2,강력범죄,강도,118,43,31,30,10,17,10,2,...,1,1,0,0,12,5,1,4,1,28
3,강력범죄,강간,1200,347,215,340,152,200,112,26,...,6,12,36,41,77,19,17,78,18,375
4,강력범죄,유사강간,219,83,43,61,32,34,14,6,...,0,2,3,2,14,4,8,13,3,52

In [14]:
df.tail()

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
33,노동범죄,노동범죄,83,37,19,14,9,21,1,0,...,1,1,6,7,5,0,9,27,13,32
34,안보범죄,안보범죄,61,13,6,7,4,4,4,2,...,0,0,0,1,1,0,2,1,12,9
35,선거범죄,선거범죄,552,138,128,104,104,50,50,14,...,3,18,25,16,53,7,21,29,124,461
36,병역범죄,병역범죄,935,164,207,400,109,68,64,20,...,8,4,25,13,56,9,12,27,303,214
37,기타범죄,기타범죄,48367,24440,8821,17865,5177,5758,4016,1009,...,401,527,1348,1286,5339,3261,1455,3575,8013,23631

In [15]:
df.head(2)

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,35,29,16,14,1,6,8,2,...,1,2,1,2,5,0,1,3,4,19
1,강력범죄,살인미수등,68,24,15,38,2,11,7,3,...,2,0,3,1,11,1,4,4,1,43

In [16]:
df.tail(2)

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
36,병역범죄,병역범죄,935,164,207,400,109,68,64,20,...,8,4,25,13,56,9,12,27,303,214
37,기타범죄,기타범죄,48367,24440,8821,17865,5177,5758,4016,1009,...,401,527,1348,1286,5339,3261,1455,3575,8013,23631

In [18]:
df.values

array([['강력범죄', '살인기수', 35, ..., 3, 4, 19],
       ['강력범죄', '살인미수등', 68, ..., 4, 1, 43],
       ['강력범죄', '강도', 118, ..., 4, 1, 28],
       ...,
       ['선거범죄', '선거범죄', 552, ..., 29, 124, 461],
       ['병역범죄', '병역범죄', 935, ..., 27, 303, 214],
       ['기타범죄', '기타범죄', 48367, ..., 3575, 8013, 23631]], dtype=object)

In [21]:
df.columns

Index(['범죄대분류', '범죄중분류', '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
       '경기 고양', '경기 과천', '경기 광명', '경기 광주', '경기 구리', '경기 군포', '경기 김포', '경기 남양주',
       '경기 동두천', '경기 부천', '경기 성남', '경기 수원', '경기 시흥', '경기 안산', '경기 안성', '경기 안양',
       '경기 양주', '경기 여주', '경기 오산', '경기 용인', '경기 의왕', '경기 의정부', '경기 이천', '경기 파주',
       '경기 평택', '경기 포천', '경기 하남', '경기 화성', '강원 강릉', '강원 동해', '강원 삼척', '강원 속초',
       '강원 원주', '강원 춘천', '강원 태백', '충북 제천', '충북 청주', '충북 충주', '충남 계룡', '충남 공주',
       '충남 논산', '충남 당진', '충남 보령', '충남 서산', '충남 아산', '충남 천안', '전북 군산', '전북 김제',
       '전북 남원', '전북 익산', '전북 전주', '전북 정읍', '전남 광양', '전남 나주', '전남 목포', '전남 순천',
       '전남 여수', '경북 경산', '경북 경주', '경북 구미', '경북 김천', '경북 문경', '경북 상주', '경북 안동',
       '경북 영주', '경북 영천', '경북 포항', '경남 거제', '경남 김해', '경남 밀양', '경남 사천', '경남 양산',
       '경남 진주', '경남 창원', '경남 통영', '제주 서귀포', '제주 제주', '기타도시', '도시이외'],
      dtype='object')

In [23]:
df.shape

(38, 89)

In [26]:
df['서울'].describe()

count       38.000000
mean      7046.789474
std      13645.657137
min         25.000000
25%        131.500000
50%        863.000000
75%       4333.500000
max      52034.000000
Name: 서울, dtype: float64

In [27]:
df['서울'].max()

np.int64(52034)

In [28]:
df['서울'].min()

np.int64(25)

In [39]:
sum = df['서울'].sum()

In [40]:
count = df['서울'].count()

In [41]:
print(sum/count)

7046.789473684211

In [47]:
df['세종'].mean()

np.float64(171.71052631578948)

In [48]:
df

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,35,29,16,14,1,6,8,2,...,1,2,1,2,5,0,1,3,4,19
1,강력범죄,살인미수등,68,24,15,38,2,11,7,3,...,2,0,3,1,11,1,4,4,1,43
2,강력범죄,강도,118,43,31,30,10,17,10,2,...,1,1,0,0,12,5,1,4,1,28
3,강력범죄,강간,1200,347,215,340,152,200,112,26,...,6,12,36,41,77,19,17,78,18,375
4,강력범죄,유사강간,219,83,43,61,32,34,14,6,...,0,2,3,2,14,4,8,13,3,52
5,강력범죄,강제추행,4358,1064,648,1030,391,500,311,73,...,23,25,66,97,232,38,84,201,18,848
6,강력범죄,기타강간강제추행등,35,14,9,16,8,2,10,1,...,1,1,0,1,5,2,0,3,1,23
7,강력범죄,방화,217,89,50,70,35,40,28,8,...,5,5,4,10,24,5,9,20,0,114
8,절도범죄,절도범죄,37594,13699,9792,8895,5204,6034,3283,1110,...,308,342,1158,2114,3426,387,886,2247,43,9454
9,폭력범죄,상해,3353,2478,1568,1545,641,831,683,119,...,121,113,221,251,635,134,213,351,16,2612
10,폭력범죄,폭행,26509,8474,5629,8040,3430,4166,2574,400,...,168,246,803,800,2289,334,625,2169,53,5704
11,폭력범죄,체포감금,243,66,41,100,33,31,35,3,...,1,3,3,9,18,0,4,21,4,58
12,폭력범죄,협박,4162,1402,933,1411,424,595,397,86,...,55,54,141,127,311,61,109,386,82,1345
13,폭력범죄,약취유인,72,17,7,18,8,2,5,2,...,0,0,1,5,1,0,0,1,1,11
14,폭력범죄,폭력행위등,1075,572,277,501,196,211,198,25,...,20,17,47,33,127,47,56,97,4,352
15,폭력범죄,공갈,1056,503,189,591,113,232,71,25,...,13,7,50,59,126,21,28,72,465,358
16,폭력범죄,손괴,10240,3730,2716,3089,1457,1696,1079,250,...,102,107,302,387,1095,155,374,881,13,3486
17,지능범죄,직무유기,353,130,64,95,31,33,18,26,...,2,1,8,4,14,15,0,16,37,166
18,지능범죄,직권남용,392,156,47,78,64,51,19,21,...,2,0,18,10,14,5,4,19,58,128
19,지능범죄,증수뢰,71,17,7,21,11,13,7,1,...,0,0,3,2,7,0,0,1,11,31
20,지능범죄,통화,172,20,27,29,10,7,1,3,...,0,0,0,1,2,0,0,2,12,13
21,지능범죄,문서인장,2033,897,459,581,319,336,206,70,...,27,19,62,57,184,28,35,146,626,843
22,지능범죄,유가증권인지,25,7,3,0,1,0,0,0,...,0,0,0,1,0,0,0,1,2,1
23,지능범죄,사기,52034,26847,14836,16652,8249,11734,5615,1528,...,568,625,2055,2583,7204,1193,1599,3996,25191,16295
24,지능범죄,횡령,16368,4469,2643,4175,1666,1456,759,248,...,44,51,265,231,1069,117,225,646,993,2080
25,지능범죄,배임,791,273,106,184,112,105,72,13,...,7,7,17,17,70,9,12,52,176,263
26,풍속범죄,성풍속범죄,4924,1602,1125,1507,577,733,449,120,...,27,34,126,112,391,39,82,216,786,747
27,풍속범죄,도박범죄,545,384,138,239,102,181,248,13,...,2,6,23,7,53,9,13,49,110,290
28,특별경제범죄,특별경제범죄,10374,3996,1917,3025,1332,1226,794,169,...,55,66,277,376,796,114,186,595,2460,2025
29,마약범죄,마약범죄,2821,856,306,1062,129,101,107,29,...,23,18,51,55,226,62,7,44,71,1000
30,보건범죄,보건범죄,4260,2581,777,1048,431,303,347,60,...,71,54,93,104,291,68,47,170,108,856
31,환경범죄,환경범죄,50,243,16,87,7,23,29,7,...,36,46,7,31,71,33,11,21,49,574
32,교통범죄,교통범죄,32013,12176,12610,11926,7827,6389,5754,1031,...,574,751,1573,1376,4023,825,1382,3052,323,20094
33,노동범죄,노동범죄,83,37,19,14,9,21,1,0,...,1,1,6,7,5,0,9,27,13,32
34,안보범죄,안보범죄,61,13,6,7,4,4,4,2,...,0,0,0,1,1,0,2,1,12,9
35,선거범죄,선거범죄,552,138,128,104,104,50,50,14,...,3,18,25,16,53,7,21,29,124,461
36,병역범죄,병역범죄,935,164,207,400,109,68,64,20,...,8,4,25,13,56,9,12,27,303,214
37,기타범죄,기타범죄,48367,24440,8821,17865,5177,5758,4016,1009,...,401,527,1348,1286,5339,3261,1455,3575,8013,23631

In [56]:
df['범죄대분류'].unique()

array(['강력범죄', '절도범죄', '폭력범죄', '지능범죄', '풍속범죄', '특별경제범죄', '마약범죄', '보건범죄',
       '환경범죄', '교통범죄', '노동범죄', '안보범죄', '선거범죄', '병역범죄', '기타범죄'],
      dtype=object)

In [57]:
df['범죄대분류'].nunique()

15